# Generated by Django 4.2.18 on 2025-02-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_candidates", models.IntegerField(verbose_name="候选人数量")),
                ("interviewed", models.IntegerField(verbose_name="已面试人数")),
                ("passed", models.IntegerField(verbose_name="通过人数")),
                (
                    "report_date",
                    models.DateField(auto_now_add=True, verbose_name="统计日期"),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                        verbose_name="职位",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘进度",
                "verbose_name_plural": "招聘进度",
                "ordering": ["-report_date"],
                "get_latest_by": "report_date",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentEffectiveness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_to_fill",
                    models.IntegerField(
                        help_text="从职位发布到成功招聘的天数",
                        verbose_name="职位填充时间(天)",
                    ),
                ),
                (
                    "cost_per_hire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="每个职位的平均招聘成本",
                        max_digits=10,
                        verbose_name="招聘成本",
                    ),
                ),
                (
                    "source_effectiveness",
                    models.JSONField(
                        help_text="各招聘渠道的效果数据", verbose_name="招聘渠道效果"
                    ),
                ),
                (
                    "report_date",
                    models.DateField(auto_now_add=True, verbose_name="统计日期"),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                        verbose_name="职位",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘效果",
                "verbose_name_plural": "招聘效果",
                "ordering": ["-report_date"],
                "get_latest_by": "report_date",
            },
        ),
    ]
