# Generated by Django 4.2.18 on 2025-02-02 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=200, verbose_name="检索关键词")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="检索时间"),
                ),
                (
                    "results_count",
                    models.IntegerField(default=0, verbose_name="结果数量"),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("keyword", "关键词"),
                            ("semantic", "语义"),
                            ("vector", "向量"),
                        ],
                        default="keyword",
                        max_length=20,
                        verbose_name="检索类型",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="检索用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "检索记录",
                "verbose_name_plural": "检索记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
