# Generated by Django 4.2.18 on 2025-02-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resumesearch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumesearch",
            name="search_type",
        ),
    ]
