# Generated by Django 4.2.18 on 2025-02-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_remove_resumesearch_search_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumesearch",
            name="filters",
            field=models.JSONField(
                blank=True,
                help_text="存储多条件检索的参数",
                null=True,
                verbose_name="检索条件",
            ),
        ),
        migrations.AddField(
            model_name="resumesearch",
            name="search_type",
            field=models.CharField(
                choices=[
                    ("keyword", "关键词"),
                    ("education", "教育背景"),
                    ("experience", "工作经历"),
                    ("skill", "技能要求"),
                    ("comprehensive", "综合检索"),
                ],
                default="keyword",
                max_length=20,
                verbose_name="检索类型",
            ),
        ),
    ]
