# Generated by Django 4.2.18 on 2025-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="职位名称")),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="所属部门"),
                ),
                ("description", models.TextField(verbose_name="职位描述")),
                ("requirements", models.TextField(verbose_name="任职要求")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "招聘中"),
                            ("closed", "已关闭"),
                            ("draft", "草稿"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "职位",
                "verbose_name_plural": "职位",
                "ordering": ["-created_at"],
            },
        ),
    ]
