# Generated by Django 4.2.18 on 2025-02-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "候选人",
                "verbose_name_plural": "候选人",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="评分")),
                ("comments", models.TextField(verbose_name="评语")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidate",
                        verbose_name="候选人",
                    ),
                ),
            ],
            options={
                "verbose_name": "评估记录",
                "verbose_name_plural": "评估记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
