# Generated by Django 4.2.18 on 2025-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LanguageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("zhipu", "智谱AI"),
                            ("deepseek", "Deepseek"),
                            ("qianwen", "通义千问"),
                        ],
                        max_length=20,
                        verbose_name="模型类型",
                    ),
                ),
                ("api_url", models.URLField(verbose_name="API地址")),
                ("api_key", models.CharField(max_length=200, verbose_name="API密钥")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("temperature", models.FloatField(default=0.7, verbose_name="温度")),
                (
                    "max_tokens",
                    models.IntegerField(default=2000, verbose_name="最大token数"),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="其他配置"),
                ),
            ],
            options={
                "verbose_name": "语言模型",
                "verbose_name_plural": "语言模型",
            },
        ),
    ]
