# Generated by Django 4.2.18 on 2025-02-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_time", models.DateTimeField(verbose_name="面试时间")),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "电话面试"),
                            ("video", "视频面试"),
                            ("onsite", "现场面试"),
                        ],
                        max_length=20,
                        verbose_name="面试类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已安排"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="面试反馈")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidate",
                        verbose_name="候选人",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                        verbose_name="应聘职位",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试",
                "verbose_name_plural": "面试",
                "ordering": ["-interview_time"],
            },
        ),
    ]
